version: '2'
services:
  cloudbrain-http:
    build: .
    ports:
      - 42191:42191
    volumes:
      - .:/code
    env_file:
      - dev.env
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
    command: [ "/go/src/github.com/travis-ci/cloud-brain/bin/cloudbrain-http" ]
  cloudbrain-create-worker:
    build: .
    volumes:
      - .:/code
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
    env_file:
      - dev.env
    environment:
      - CLOUDBRAIN_DATABASE_ENCRYPTION_KEY=e266185db2078529ebfc4e3e93767491e266185db2078529ebfc4e3e93767491
    command: [ "/go/src/github.com/travis-ci/cloud-brain/bin/cloudbrain-create-worker" ]
  cloudbrain-refresh-worker:
    build: .
    volumes:
      - .:/code
    depends_on:
      - redis
      - postgres
    env_file:
      - dev.env
    environment:
      - CLOUDBRAIN_DATABASE_ENCRYPTION_KEY=e266185db2078529ebfc4e3e93767491e266185db2078529ebfc4e3e93767491
    command: [ "/go/src/github.com/travis-ci/cloud-brain/bin/cloudbrain-refresh-worker" ]
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=cloudbrain
      - POSTGRES_PASSWORD=travis
    ports:
      - 5432:5432
