version: '2'
services:
  cloudbrain-http:
    build: .
    ports:
      - 42191:42191
    volumes:
     - .:/code
    links:
      - redis
      - postgres
    depends_on:
     - redis
     - postgres
    environment: 
     - REDIS_URL=redis://redis:6379
     - DATABASE_URL=postgres://postgres:5432/?sslmode=disable
     - DEBUG=1
    command: [ "/go/src/github.com/travis-ci/cloud-brain/bin/cloudbrain-http" ]
  cloudbrain-create-worker:
    build: .
    volumes:
     - .:/code
    links:
      - redis
      - postgres
    depends_on:
     - redis
     - postgres
    environment: 
     - REDIS_URL=redis://redis:6379
     - DATABASE_URL=postgres://postgres:5432/?sslmode=disable
     - DEBUG=1
     - CLOUDBRAIN_DATABASE_ENCRYPTION_KEY=e266185db2078529ebfc4e3e93767491e266185db2078529ebfc4e3e93767491
    command: [ "/go/src/github.com/travis-ci/cloud-brain/bin/cloudbrain-create-worker" ]
  cloudbrain-refresh-worker:
    build: .
    volumes:
     - .:/code
    depends_on:
     - redis
     - postgres
    environment: 
     - REDIS_URL=redis://redis:6379
     - DATABASE_URL=postgres://postgres:5432/?sslmode=disable
     - DEBUG=1
     - CLOUDBRAIN_DATABASE_ENCRYPTION_KEY=e266185db2078529ebfc4e3e93767491e266185db2078529ebfc4e3e93767491
    command: [ "/go/src/github.com/travis-ci/cloud-brain/bin/cloudbrain-refresh-worker" ]
  redis:
    image: redis
    expose: 
      - 6379
  postgres:
    image: postgres
    expose: 
      - 5432
